services:
  postgresql:
    container_name: postgresql
    image: postgres:17.5-bullseye
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - ./database/postgresql/oc3:/var/lib/postgresql/data
    networks:
      - olympia-custom-network
    profiles:
      - production
      - development

  valkey:
    container_name: valkey
    image: valkey/valkey:9-alpine
    command: >
      valkey-server 
      --requirepass ${VALKEY_PASSWORD}
      --user ${VALKEY_USER} on >${VALKEY_PASSWORD} ~* +@all
    ports:
      - "${VALKEY_PORT}:6379"
    networks:
      - olympia-custom-network
    profiles:
      - production
      - development

  app:
    container_name: app
    build:
      context: ./backend/app
    volumes:
      - ./backend/app:/backend/app
    depends_on:
      - postgresql
      - valkey
    ports:
      - "8000:8000"
    networks:
      - olympia-custom-network
    profiles:
      - production
      - development

networks:
  olympia-custom-network:
    driver: bridge

volumes:
  postgres_data:
